version: '3.5'
services:
  app:
    image: ${TEST_IMAGE_NAME:-jimsihk/alpine-moodle:local}
    build: .
    environment:
      - SITE_URL=http://app:8080
      - MOODLE_SITENAME=Dockerized_Moodle
      - SESSION_CACHE_TYPE=redis
      - SESSION_CACHE_HOST=redis
      - SESSION_CACHE_PORT=6379
      - AUTO_UPDATE_MOODLE=false
      - UPDATE_MOODLE_CODE=false
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:alpine
    environment:
      - POSTGRES_PASSWORD=moodle
      - POSTGRES_USER=moodle
      - POSTGRES_DB=moodle
        
  redis:
    image: redis/redis-stack-server

  sut:
    image: alpine:latest
    depends_on:
      - app
    environment:
      - SOURCE_BRANCH
    command: /tmp/run_tests.sh
    volumes:
      - "./run_tests.sh:/tmp/run_tests.sh:ro"
