services:

  postgres:
    image: postgres:alpine
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=moodle
      - POSTGRES_USER=moodle
      - POSTGRES_DB=moodle
    volumes:
      - postgres:/var/lib/postgresql/data

  app:
    image: ${TEST_IMAGE_NAME:-jimsihk/alpine-moodle:local}
    build:
      context: .
      args:
        - ARG_MOODLE_GIT_COMMIT=${ARG_MOODLE_GIT_COMMIT}
        - ARG_MOODLE_GIT_BRANCH=${ARG_MOODLE_GIT_BRANCH}
    restart: unless-stopped
    environment:
      - LANG=en_US.UTF-8
      - LANGUAGE=en_US:en
      - SITE_URL=http://app:8080
      - DB_TYPE=pgsql
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=moodle
      - DB_USER=moodle
      - DB_PASS=moodle
      - DB_PREFIX=mdl_
      - SSLPROXY=false
      - MOODLE_EMAIL=user@example.com
      - MOODLE_LANGUAGE=en
      - MOODLE_SITENAME=Dockerized_Moodle
      - MOODLE_USERNAME=moodleuser
      - MOODLE_PASSWORD=PLEASE_CHANGEME
      - SMTP_HOST=smtp.gmail.com
      - SMTP_PORT=587
      - SMTP_USER=your_email@gmail.com
      - SMTP_PASSWORD=your_password
      - SMTP_PROTOCOL=tls
      - MOODLE_MAIL_NOREPLY_ADDRESS=noreply@localhost
      - MOODLE_MAIL_PREFIX=[moodle]
      - SESSION_CACHE_TYPE=database
      - SESSION_CACHE_HOST=postgres
      - SESSION_CACHE_PORT=5432
      - SESSION_CACHE_PREFIX=mdl
      - AUTO_UPDATE_MOODLE=${AUTO_UPDATE_MOODLE:-false}
      - UPDATE_MOODLE_CODE=${UPDATE_MOODLE_CODE:-false}
    volumes:
      - ${LOCAL_PATH:-./tmpdata}/moodledata:/var/www/moodledata
      - ${LOCAL_PATH:-./tmpdata}/moodlehtml:/var/www/html
    depends_on:
      - postgres

  sut:
    image: alpine:latest
    depends_on:
      - app
    command: /tmp/run_tests.sh
    volumes:
      - "./run_tests.sh:/tmp/run_tests.sh:ro"

volumes:
  postgres: null
