#!/bin/sh
#
# Moodle code plugin installation wrapper script
# Description: Install additional plugins using the current Moodle Marketplace
#              compatible installer. Component-name lookup via the retired
#              download.moodle.org Plugins API is no longer used.
#

UTL_PATH=/usr/libexec/moodle

if [ -n "${MOODLE_PLUGIN_LIST}" ]; then
  if [ -n "${ALLOW_INCOMPATIBLE_PLUGIN}" ] && [ "${ALLOW_INCOMPATIBLE_PLUGIN}" = 'true' ]; then
    "$UTL_PATH"/install-plugin-list-marketplace -p "${MOODLE_PLUGIN_LIST}"
    if [ $? -ne 0 ]; then
      exit 2
    fi
  else
    "$UTL_PATH"/install-plugin-list-marketplace -p "${MOODLE_PLUGIN_LIST}"
    if [ $? -ne 0 ]; then
      exit 3
    fi
  fi
fi
rm -rf /tmp/moodle-plugins
