name: Build and test PR

on:
  pull_request:
    branches: ["dev"]
    paths-ignore:
      - README.md

jobs:
  prepare:
    outputs:
      tag: ${{ steps.meta.outputs.tags }}
    runs-on: ubuntu-latest
    steps:
      - uses: step-security/harden-runner@v2
        with:
          egress-policy: audit

      - name: Prepare Meta Data
        id: meta
        uses: docker/metadata-action@v6
        with:
          images: |
            localhost:5000/${{ github.repository }}
          tags: |
            type=sha
    
  test:
    strategy:
      fail-fast: false
      matrix:
        test: [standard, slim, multi, volume1, volume2]
    needs:
      - prepare
    runs-on: ubuntu-latest
    timeout-minutes: 60
    services:
      registry:
        image: registry:3
        ports:
          - 5000:5000
    steps:
      - uses: step-security/harden-runner@v2
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@v6

      - name: Set up QEMU
        if: matrix.test == 'multi'
        uses: docker/setup-qemu-action@v4

      - name: Set up Docker Buildx
        if: matrix.test == 'multi'
        uses: docker/setup-buildx-action@v4
        with:
          driver-opts: network=host

      - name: Build and Test
        if: matrix.test == 'standard'
        run: |
          LOCAL_TEST_IMAGE_NAME="$(echo '${{ needs.prepare.outputs.tag }}' | sed 's#^localhost:5000/##')"
          echo '###############################'
          echo "Test - build with plugin list and installing Moodle..."
          export TEST_IMAGE_NAME="${LOCAL_TEST_IMAGE_NAME}"
          export ARG_MOODLE_PLUGIN_LIST=report_benchmark
          docker compose --file docker-compose.test.yml up --exit-code-from sut -t 10
          docker compose --file docker-compose.test.yml down --remove-orphans

          echo '#'
          echo '###############################'
          echo "Test - Moodle update and plugin installation..."
          export TEST_IMAGE_NAME=${{ github.repository }}:latest
          docker compose --file docker-compose.test.yml up --exit-code-from sut -t 10
          export TEST_IMAGE_NAME="${LOCAL_TEST_IMAGE_NAME}"
          export AUTO_UPDATE_MOODLE=true
          export UPDATE_MOODLE_CODE=true
          docker compose --file docker-compose.test.yml up --exit-code-from sut -t 10
          docker compose --file docker-compose.test.yml down --remove-orphans
          unset AUTO_UPDATE_MOODLE UPDATE_MOODLE_CODE

      - name: Test Bind Volume Mount
        if: matrix.test == 'volume1'
        run: |
          LOCAL_TEST_IMAGE_NAME="$(echo '${{ needs.prepare.outputs.tag }}' | sed 's#^localhost:5000/##')"
          echo '###############################'
          echo "Test - run with bind volume..."
          export LOCAL_PATH='./tmpdata/'"${{ matrix.test }}"
          mkdir -p "${LOCAL_PATH}"/moodledata "${LOCAL_PATH}"/moodlehtml
          chmod -R 777 "${LOCAL_PATH}"
          export ARG_MOODLE_GIT_BRANCH="$(grep '^ARG\s*ARG_MOODLE_GIT_BRANCH=' Dockerfile | cut -d '=' -f 2 | tr -d "'")"
          export ARG_MOODLE_GIT_COMMIT="$(grep '^ARG\s*ARG_MOODLE_GIT_COMMIT=' Dockerfile | cut -d '=' -f 2 | tr -d "'")"
          export TEST_IMAGE_NAME="${LOCAL_TEST_IMAGE_NAME}"
          docker compose --file docker-compose.test.volume.yml up --exit-code-from sut -t 10
          docker compose --file docker-compose.test.volume.yml down --remove-orphans
          echo "${LOCAL_PATH}"
          ls -l "${LOCAL_PATH}"

      - name: Test Upgrade with Bind Volume Mount
        if: matrix.test == 'volume2'
        run: |
          LOCAL_TEST_IMAGE_NAME="$(echo '${{ needs.prepare.outputs.tag }}' | sed 's#^localhost:5000/##')"
          echo '###############################'
          echo "Test - Moodle update by Git with volume..."
          export LOCAL_PATH='./tmpdata'"${{ matrix.test }}"
          mkdir -p "${LOCAL_PATH}"/moodledata "${LOCAL_PATH}"/moodlehtml
          chmod -R 777 "${LOCAL_PATH}"
          export TEST_IMAGE_NAME=${{ github.repository }}:latest
          #export ARG_MOODLE_GIT_BRANCH='MOODLE_405_STABLE'
          #export ARG_MOODLE_GIT_COMMIT='a57387fe2d8faa2e6fa36246f4dc59825c307e7f'
          #export TEST_IMAGE_NAME=${{ needs.prepare.outputs.tag }}-old
          docker compose --file docker-compose.test.volume.yml up --exit-code-from sut -t 10
          echo "${LOCAL_PATH}"
          ls -l "${LOCAL_PATH}"

          export AUTO_UPDATE_MOODLE=true
          export UPDATE_MOODLE_CODE=true
          export ARG_MOODLE_GIT_BRANCH="$(grep '^ARG\s*ARG_MOODLE_GIT_BRANCH=' Dockerfile | cut -d '=' -f 2 | tr -d "'")"
          export ARG_MOODLE_GIT_COMMIT="$(grep '^ARG\s*ARG_MOODLE_GIT_COMMIT=' Dockerfile | cut -d '=' -f 2 | tr -d "'")"
          export TEST_IMAGE_NAME="${LOCAL_TEST_IMAGE_NAME}"
          docker compose --file docker-compose.test.volume.yml up --exit-code-from sut -t 10

          docker compose --file docker-compose.test.volume.yml down --remove-orphans
          unset AUTO_UPDATE_MOODLE UPDATE_MOODLE_CODE
          #rm -rf ./tmpdata #TODO: fix permission denied error

      - name: Build and Test (Slim)
        if: matrix.test == 'slim'
        run: |
          LOCAL_TEST_IMAGE_NAME="$(echo '${{ needs.prepare.outputs.tag }}' | sed 's#^localhost:5000/##')-slim"
          echo '###############################'
          echo "Test - build with plugin list and installing Moodle..."
          export TEST_IMAGE_NAME="${LOCAL_TEST_IMAGE_NAME}"
          export ARG_MOODLE_PLUGIN_LIST=report_benchmark
          export ARG_ENABLE_GIT_CLONE=false
          docker compose --file docker-compose.test.yml up --exit-code-from sut -t 10
          docker compose --file docker-compose.test.yml down --remove-orphans

          echo '#'
          echo '###############################'
          echo "Test - Moodle update and plugin installation..."
          export TEST_IMAGE_NAME=${{ github.repository }}:latest-slim
          docker compose --file docker-compose.test.yml up --exit-code-from sut -t 10
          export TEST_IMAGE_NAME="${LOCAL_TEST_IMAGE_NAME}"
          export AUTO_UPDATE_MOODLE=true
          export UPDATE_MOODLE_CODE=true
          docker compose --file docker-compose.test.yml up --exit-code-from sut -t 10
          docker compose --file docker-compose.test.yml down --remove-orphans
          unset AUTO_UPDATE_MOODLE UPDATE_MOODLE_CODE
          unset ARG_ENABLE_GIT_CLONE

      - name: Test build multi-arch
        if: matrix.test == 'multi'
        uses: docker/build-push-action@v7
        with:
          context: .
          push: true # to local registry
          tags: ${{ needs.prepare.outputs.tag }}
          platforms: ${{ vars.CONTAINER_ARCH }}
          provenance: false

      - name: Run Trivy vulnerability scanner for PR
        if: matrix.test == 'multi'
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ needs.prepare.outputs.tag }}
          format: 'table'
          severity: 'CRITICAL,HIGH'
          exit-code: 0
        env:
          TRIVY_DB_REPOSITORY: ghcr.io/aquasecurity/trivy-db,public.ecr.aws/aquasecurity/trivy-db

      - name: Run Anchore scan for PR
        if: matrix.test == 'multi'
        uses: anchore/scan-action@v7
        id: anchore-scan-pr
        with:
          image: ${{ needs.prepare.outputs.tag }}
          output-format: table
          fail-build: false

  final:
    if: always()
    needs: 
      - test
    runs-on: ubuntu-latest
    steps:
      - uses: step-security/harden-runner@v2
        with:
          egress-policy: audit

      - name: Check necessary test status
        uses: re-actors/alls-green@release/v1
        with:
          jobs: ${{ toJSON(needs) }}
