name: Update DockerHub Description

on:
  push:
    branches: ["dev"]
    paths:
      - README.md
      - .github/workflows/update-dockerhub-desc.yml

jobs:
  update-dockerhub-desc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4

      - name: Update Docker Hub Description
        uses: peter-evans/dockerhub-description@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          short-description: ${{ github.event.repository.description }}